#!/usr/bin/perl

# Copyright (c) 2017 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;

use WebService::Coinbase;
our $key;
our $secret;

open(C,$ENV{'HOME'}."/.coinbase.conf");
chomp($key=<C>);
chomp($secret=<C>);
close(C);
if (!defined($key) || !defined($secret)) {
	die "key and secret must be in \$HOME/.coinbase.conf";
}

my $ws = WebService::Coinbase->new(
	api_key	=> $key,
	api_secret => $secret,
	# logger => Log::Tiny->new('/tmp/coinbase.log'), # optional
);
if (!defined($ws)) {
	print "WebService::Coinbase->new() returned undef\n";
	exit(1);
}
my $accounts = $ws->get_accounts();
print "get_accounts returned a ".ref($accounts)."\n";
